# Meta Data for SEO

## Homepage
title = "Cactus Comments"
titleSeparator = "-"
titleAddition = "Federated Web Comments"
description = "Cactus Comments is a federated comment system for the web."

## Open Graph + Twitter Cards
images = ["doks.png"]
ogLocale = "en_US"

## JSON-LD
schemaType = "Organization"
schemaLogo = "logo-doks.png"
schemaGitHub = "https://gitlab.com/cactus-comments"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = ""

# Alert
alert = false
alertText = "Like Cactus Comments? <a class=\"alert-link\" href=\"https://gitlab.com/cactus-comments/\">Star us on GitLab</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/h-enk/doks"
editPage = false
